[project]
name = "cast-deceased"
version = "0.1.0"
description = "Find out if an actor from a movie is still alive "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cinemagoer>=2023.5.1",
    "streamlit>=1.45.1",
]
